name: Auto Release

on:
  push:
    branches: [main]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for release tag
        id: check_tag
        run: |
          if [ -f .commit_has_release_tag ]; then
            MESSAGE=$(git log -1 --pretty=%B)
            VERSION=$(echo "$MESSAGE" | grep -oE 'v[0-9]+')
            echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
            echo "✔ Versão detectada: $VERSION"
          fi

      - name: Create Release
        if: env.RELEASE_VERSION != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: "Release ${{ env.RELEASE_VERSION }}"
          body: "Automated release | Commit: ${{ github.sha }}"
          draft: false
          prerelease: false
