name: Auto Release

on:
  push:
    branches: [main]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Crucial para acessar histórico

      - name: Extract version
        id: extract
        run: |
          MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit Message: '$MESSAGE'"
          
          # Regex melhorado (case insensitive, ignora espaços)
          if [[ "$MESSAGE" =~ [vV][0-9]+ ]]; then
            VERSION=$(echo "$MESSAGE" | grep -oi 'v[0-9]\+' | head -1)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "✅ Versão detectada: $VERSION"
          else
            echo "❌ Nenhuma versão encontrada"
          fi

      - name: Create Release
        if: ${{ steps.extract.outputs.version != '' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract.outputs.version }}
          release_name: "Release ${{ steps.extract.outputs.version }}"
          body: "Automated release | Commit: ${{ github.sha }}"
          draft: false
          prerelease: false