name: Release Please

on:
  push:
    branches:
      - main  # ou "master", se for o seu caso

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node  # ou 'simple', se não for Node.js
          token: ${{ secrets.GITHUB_TOKEN }}
